Repository oracle/mysql-operator, pull requests merged in 2018-09, with the labels that each got.

#218 Add support for defining securityContext in cluster spec
  pkg/apis/mysql/v1alpha1/types.go
  pkg/resources/statefulsets/statefulset.go
  pkg/resources/statefulsets/statefulset_test.go
Labels: enhancement, feature, oracle-cla: yes

#217 Fix installing in a different namespace
  mysql-operator/templates/02-rbac.yaml
Labels: bug, oracle-cla: yes

#223 Update README badges with tags and issues
  README.md
Labels: documentation
