Repository oracle/mysql-operator, pull requests merged in 2018-08, with the labels that each got.

#192 Fixes gofmt issues introduced to master
  cmd/mysql-agent/app/mysql_agent.go
  cmd/mysql-operator/app/mysql_operator.go
  pkg/controllers/cluster/controller_test.go
  pkg/resources/statefulsets/statefulset.go
  pkg/resources/statefulsets/statefulset_test.go
Labels: bug

#199 Set MySQL 8.0.12 as default version
  docker/mysql-agent/Dockerfile
  pkg/apis/mysql/v1alpha1/helpers.go
Labels: enhancement

#204 Add mysqlclusters/finalizers to RBAC
  contrib/manifests/rbac.yaml
  mysql-operator/Chart.yaml
  mysql-operator/templates/02-rbac.yaml
Labels: bug

#206 Update router documentation
  docs/user/router.md
Labels: documentation

#207 Implement MySQL version upgrade support
  pkg/controllers/cluster/controller.go
  pkg/controllers/cluster/controller_test.go
  pkg/resources/statefulsets/statefulset.go
  test/e2e/framework/cluster.go
  test/e2e/upgrade.go
Labels: enhancement, feature

#209 fix backups to disk
  pkg/backup/executor/mysqldump/provider.go
Labels: enhancement, feature, oracle-cla: yes

#213 Add BackupOperator UpdateFunc and fix duplicate backups
  pkg/controllers/backup/agent_controller.go
  pkg/controllers/backup/operator_controller.go
Labels: enhancement, oracle-cla: yes

#215 Fix repeated execution of restore operations
  pkg/controllers/cluster/cluster_control.go
  pkg/controllers/restore/agent_controller.go
Labels: enhancement
