Repository oracle/mysql-operator, pull requests merged in 2018-07, with the labels that each got.

#157 Fix restarting the entire cluster when volumes are persisted
  pkg/util/mysqlsh/mysqlsh.go
Labels: oracle-cla: yes

#167 Simplify and improve the local developer experience for pushing images
  Makefile
Labels: enhancement

#169 Implement minimum MySQL version validation
  Gopkg.lock
  Gopkg.toml
  pkg/apis/mysql/v1alpha1/cluster_test.go
  pkg/apis/mysql/v1alpha1/helpers.go
  pkg/apis/mysql/v1alpha1/types.go
  pkg/apis/mysql/v1alpha1/validation.go
  vendor/github.com/coreos/go-semver/.travis.yml
  vendor/github.com/coreos/go-semver/DCO
  vendor/github.com/coreos/go-semver/LICENSE
  vendor/github.com/coreos/go-semver/NOTICE
  vendor/github.com/coreos/go-semver/README.md
  vendor/github.com/coreos/go-semver/code-of-conduct.md
  vendor/github.com/coreos/go-semver/example.go
  vendor/github.com/coreos/go-semver/semver/semver.go
  vendor/github.com/coreos/go-semver/semver/semver_test.go
  vendor/github.com/coreos/go-semver/semver/sort.go
Labels: enhancement

#171 Add report card badge
  README.md
Labels: documentation

#173 Update Chart.yaml to reflect operator 0.2.0 version
  mysql-operator/Chart.yaml
Labels: documentation

#176 Tidy up issues highlighted by Go Report Card
  pkg/apis/mysql/v1alpha1/types.go
  pkg/cluster/innodb/innodb_test.go
  pkg/controllers/cluster/controller.go
  pkg/controllers/cluster/controller_test.go
  pkg/controllers/cluster/labeler/cluster_labeler_test.go
  pkg/resources/statefulsets/statefulset.go
Labels: enhancement

#187 Use --decode for cross OS compatibility
  docs/tutorial.md
Labels: documentation

#189 Code refactor on options
  cmd/mysql-agent/app/mysql_agent.go
  cmd/mysql-agent/main.go
  cmd/mysql-operator/app/mysql_operator.go
  cmd/mysql-operator/main.go
  pkg/controllers/cluster/controller.go
  pkg/controllers/cluster/controller_test.go
  pkg/options/agent/options.go
  pkg/options/operator/options.go
  pkg/options/operator/options_test.go
  pkg/resources/statefulsets/statefulset.go
  pkg/resources/statefulsets/statefulset_test.go
Labels: oracle-cla: yes
