Repository oracle/mysql-operator, pull requests merged in 2018-06, with the labels that each got.

#118 Add Development.md documentation
  contrib/manifests/custom-resource-definitions.yaml
  contrib/manifests/rbac.yaml
  contrib/manifests/role-binding-template.yaml
  docs/development.md
Labels: documentation

#121 Independent mysql-agent ClusterRole and RBAC
  README.md
  cmd/mysql-operator/app/mysql_operator.go
  contrib/manifests/rbac.yaml
  docs/tutorial.md
  mysql-operator/templates/02-rbac.yaml
  mysql-operator/values.yaml
  pkg/controllers/cluster/config_control.go
  pkg/controllers/cluster/controller.go
  pkg/controllers/cluster/controller_test.go
  pkg/controllers/cluster/secret_control.go
  pkg/controllers/cluster/service_control.go
  pkg/controllers/cluster/statefulset_control.go
  pkg/controllers/cluster/statefulset_control_test.go
  wercker.yml
Labels: enhancement, security

#141 Fix mysql-agent InvalidImageName
  mysql-operator/templates/03-deployment.yaml
Labels: bug

#142 Fix CRD and RBAC issues when installing 0.1.x via helm
  mysql-operator/templates/01-resources.yaml
  mysql-operator/templates/02-rbac.yaml
Labels: bug

#146 Some improvements to the installation tutorial
  docs/tutorial.md
Labels: documentation

#130 Fix cluster config (alpha1 -> v1alpha1)
  examples/cluster/cluster-with-custom-config.yaml
Labels: oracle-cla: yes

#131 Properly exclude the local instance from the seeds list
  pkg/controllers/cluster/manager/innodb_cluster.go
  pkg/controllers/cluster/manager/innodb_cluster_test.go
Labels: oracle-cla: yes

#132 Workaround for sanitizing JSON coming from MySQL Shell
  pkg/util/mysqlsh/mysqlsh.go
Labels: oracle-cla: yes

#155 Restore native dba.reboot_cluster_from_complete_outage()
  pkg/util/mysqlsh/mysqlsh.go
Labels: enhancement, oracle-cla: yes
