Repository oracle/mysql-operator, pull requests merged in 2018-05, with the labels that each got.

#91 Fix typo in mysqlsh/options
  pkg/util/mysqlsh/options.go
Labels: documentation

#95 Use correct name for secret in WP example
  examples/demo/wordpress/wordpress-deployment.yaml
Labels: bug, documentation

#99 Remove unwanted command line arguments
  pkg/resources/statefulsets/statefulset.go
Labels: enhancement

#115 Group replication SSL
  .gitignore
  examples/cluster/cluster-with-custom-ssl-certs.yaml
  examples/custom-ssl-secret.yaml
  pkg/apis/mysql/v1/cluster.go
  pkg/apis/mysql/v1/cluster_test.go
  pkg/controllers/cluster/manager/cluster_manager.go
  pkg/resources/statefulsets/statefulset.go
  pkg/resources/statefulsets/statefulset_test.go
Labels: enhancement

#116 No need for an async healthcheck now we're caching
  Makefile
  cmd/mysql-agent/app/mysql_agent.go
  pkg/cluster/cluster_health.go
  pkg/controllers/cluster/manager/cluster_manager.go
  pkg/util/mysqlsh/mysqlsh.go
Labels: enhancement
