Repository oracle/mysql-operator, pull requests merged in 2018-04, with the labels that each got.

#67 Use official mysql-router image for examples
  examples/demo/wordpress-router/wordpress-deployment.yaml
Labels: enhancement

#78 Set MySQL container to log to stderr
  pkg/resources/statefulsets/statefulset.go
Labels: enhancement

#81 Fix logging before flag.Parse
  cmd/mysql-agent/main.go
  cmd/mysql-operator/app/options/options.go
  cmd/mysql-operator/main.go
Labels: bug

#73 Allow to set base server id
  docs/user/clusters.md
  pkg/apis/mysql/v1/cluster.go
  pkg/apis/mysql/v1/cluster_test.go
  pkg/apis/mysql/v1/validate_cluster.go
  pkg/resources/statefulsets/statefulset.go
Labels: enhancement

#87 Upgrade to MySQL 8.0.11 (GA)
  Makefile
  cmd/mysql-agent/app/mysql_agent.go
  docker/mysql-agent/Dockerfile
  examples/backup/backup-schedule.yaml
  examples/backup/backup.yaml
  examples/cluster/cluster-with-3-replicas.yaml
  examples/cluster/cluster-with-custom-config.yaml
  examples/cluster/cluster-with-custom-secret.yaml
  examples/cluster/cluster-with-data-volume-and-backup-volume.yaml
  examples/cluster/cluster-with-volume.yaml
  examples/cluster/cluster.yaml
  examples/cluster/multi-master-cluster.yaml
  examples/demo/wordpress-router/wordpress-database.yaml
  examples/demo/wordpress-router/wordpress-deployment.yaml
  examples/restore/restore.yaml
  hack/mysql.sh
  hack/mysqlsh-py.sh
  pkg/apis/mysql/v1/cluster.go
  pkg/apis/mysql/v1/validate_cluster.go
  pkg/cluster/cluster_health.go
  pkg/cluster/innodb/innodb.go
  pkg/cluster/instance.go
  pkg/cluster/instance_test.go
  pkg/controllers/cluster/controller.go
  pkg/controllers/cluster/controller_test.go
  pkg/controllers/cluster/labeler/cluster_labeler.go
  pkg/controllers/cluster/labeler/cluster_labeler_test.go
  pkg/controllers/cluster/manager/cluster_manager.go
  pkg/controllers/cluster/manager/innodb_cluster.go
  pkg/controllers/cluster/manager/innodb_cluster_test.go
  pkg/controllers/cluster/utils.go
  pkg/controllers/util/patch.go
  pkg/resources/statefulsets/statefulset.go
  pkg/util/mysqlsh/mysqlsh.go
  pkg/util/mysqlsh/mysqlsh_test.go
  pkg/util/mysqlsh/options.go
  pkg/util/mysqlsh/options_test.go
  test/e2e/basic_test.go
  test/e2e/util/recovery.go
  wercker.yml
Labels: enhancement, feature
